[debug] [2024-12-03T07:43:28.645Z] ----------------------------------------------------------------------
[debug] [2024-12-03T07:43:28.649Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-12-03T07:43:28.649Z] CLI Version:   13.27.0
[debug] [2024-12-03T07:43:28.650Z] Platform:      win32
[debug] [2024-12-03T07:43:28.650Z] Node Version:  v22.11.0
[debug] [2024-12-03T07:43:28.650Z] Time:          Tue Dec 03 2024 08:43:28 GMT+0100 (hora estándar de Europa central)
[debug] [2024-12-03T07:43:28.650Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-12-03T07:43:28.655Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[debug] [2024-12-03T07:43:50.609Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: 
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-12-03T07:43:50.610Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=432046567&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-12-03T07:44:49.220Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-12-03T07:44:49.220Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-12-03T07:45:10.307Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------657036475297918352781409","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 74.125.206.84:443
[debug] [2024-12-03T07:45:10.308Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\a926508\AppData\Roaming\nvm\v22.11.0\node_modules\firebase-tools\lib\apiv2.js:261:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-12-03T07:45:10.334Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-12-03T07:45:10.335Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"d07df798-aa2f-43e2-909c-e93d6611254d"}
[debug] [2024-12-03T07:45:32.224Z] *** [apiv2] error from fetch(https://auth.firebase.tools/attest, {"headers":{},"method":"POST","body":"{\"session_id\":\"d07df798-aa2f-43e2-909c-e93d6611254d\"}"}): FetchError: request to https://auth.firebase.tools/attest failed, reason: 
[debug] [2024-12-03T07:45:37.251Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\a926508\AppData\Roaming\nvm\v22.11.0\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-12-03T07:45:56.397Z] ----------------------------------------------------------------------
[debug] [2024-12-03T07:45:56.400Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-12-03T07:45:56.400Z] CLI Version:   13.27.0
[debug] [2024-12-03T07:45:56.401Z] Platform:      win32
[debug] [2024-12-03T07:45:56.401Z] Node Version:  v22.11.0
[debug] [2024-12-03T07:45:56.401Z] Time:          Tue Dec 03 2024 08:45:56 GMT+0100 (hora estándar de Europa central)
[debug] [2024-12-03T07:45:56.401Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-12-03T07:45:56.404Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=505653391&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-12-03T07:46:08.130Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-12-03T07:46:08.130Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-12-03T07:46:18.264Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: 
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-12-03T07:46:18.266Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-12-03T07:46:29.200Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------430145598831338116768750","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 74.125.206.84:443
[debug] [2024-12-03T07:46:29.201Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\a926508\AppData\Roaming\nvm\v22.11.0\node_modules\firebase-tools\lib\apiv2.js:261:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-12-03T07:46:29.212Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-12-03T07:46:29.213Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"b89a7be9-45c7-46f8-9682-87b3d3d5998a"}
[debug] [2024-12-03T07:46:51.032Z] *** [apiv2] error from fetch(https://auth.firebase.tools/attest, {"headers":{},"method":"POST","body":"{\"session_id\":\"b89a7be9-45c7-46f8-9682-87b3d3d5998a\"}"}): FetchError: request to https://auth.firebase.tools/attest failed, reason: 
[debug] [2024-12-03T07:46:56.038Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\a926508\AppData\Roaming\nvm\v22.11.0\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2024-12-03T07:48:30.669Z] ----------------------------------------------------------------------
[debug] [2024-12-03T07:48:30.672Z] Command:       C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2024-12-03T07:48:30.673Z] CLI Version:   13.27.0
[debug] [2024-12-03T07:48:30.673Z] Platform:      win32
[debug] [2024-12-03T07:48:30.673Z] Node Version:  v22.11.0
[debug] [2024-12-03T07:48:30.673Z] Time:          Tue Dec 03 2024 08:48:30 GMT+0100 (hora estándar de Europa central)
[debug] [2024-12-03T07:48:30.673Z] ----------------------------------------------------------------------
[debug] 
[debug] [2024-12-03T07:48:30.676Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[info] i  Firebase optionally collects CLI and Emulator Suite usage and error reporting information to help improve our products. Data is collected in accordance with Google's privacy policy (https://policies.google.com/privacy) and is not used to identify you.
 
[info] i  To change your data collection preference at any time, run `firebase logout` and log in again. 
[info] 
[info] Visit this URL on this device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=95247067&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2024-12-03T07:48:41.008Z] >>> [apiv2][query] POST https://accounts.google.com/o/oauth2/token [none]
[debug] [2024-12-03T07:48:41.008Z] >>> [apiv2][body] POST https://accounts.google.com/o/oauth2/token [omitted]
[debug] [2024-12-03T07:48:52.584Z] *** [apiv2] error from fetch(https://firebase-public.firebaseio.com/cli.json, {"headers":{},"method":"GET"}): FetchError: request to https://firebase-public.firebaseio.com/cli.json failed, reason: 
[warn] !  Unable to fetch the CLI MOTD and remote config. This is not a fatal error, but may indicate an issue with your network connection. 
[debug] [2024-12-03T07:48:52.585Z] Failed to fetch MOTD FirebaseError: Failed to make request to https://firebase-public.firebaseio.com/cli.json
[debug] [2024-12-03T07:49:02.092Z] *** [apiv2] error from fetch(https://accounts.google.com/o/oauth2/token, {"headers":{},"method":"POST","body":{"_overheadLength":543,"_valueLength":208,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------637483714252067072500586","_events":{},"_eventsCount":1}}): FetchError: request to https://accounts.google.com/o/oauth2/token failed, reason: connect ETIMEDOUT 74.125.206.84:443
[debug] [2024-12-03T07:49:02.094Z] Token Fetch Error: FirebaseError: Failed to make request to https://accounts.google.com/o/oauth2/token
    at RetryOperation._fn (C:\Users\a926508\AppData\Roaming\nvm\v22.11.0\node_modules\firebase-tools\lib\apiv2.js:261:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[error] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2024-12-03T07:49:02.102Z] >>> [apiv2][query] POST https://auth.firebase.tools/attest [none]
[debug] [2024-12-03T07:49:02.103Z] >>> [apiv2][body] POST https://auth.firebase.tools/attest {"session_id":"63fe3bac-95e2-4b68-becf-871a25629271"}
[debug] [2024-12-03T07:49:23.969Z] *** [apiv2] error from fetch(https://auth.firebase.tools/attest, {"headers":{},"method":"POST","body":"{\"session_id\":\"63fe3bac-95e2-4b68-becf-871a25629271\"}"}): FetchError: request to https://auth.firebase.tools/attest failed, reason: 
[debug] [2024-12-03T07:49:28.981Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\a926508\AppData\Roaming\nvm\v22.11.0\node_modules\firebase-tools\lib\utils.js:269:49)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[error] 
[error] Error: An unexpected error has occurred.
